In [ ]:
print("contoh")

contoh


In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [ ]:
print("jenis isian Dataset iris = \n", iris_dataset.keys())

jenis isian Dataset iris = 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print("target name =", iris_dataset.target_names)

target name = ['setosa' 'versicolor' 'virginica']


In [ ]:
print("Target = {}".format(iris_dataset['target']))

Target = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
print("Feature Names = {}".format(iris_dataset['feature_names']))

Feature Names = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print("Feature Names = {}".format(iris_dataset['data']))

Feature Names = [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1

In [ ]:

print("Data = {}".format(iris_dataset['data']))
print("Ukuran data = {}".format(iris_dataset['data'].shape))

Data = [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9

In [ ]:
# Proses training dan testing

ffrom sklearn.model_selection import train_test_split
data = iris_datasets['data']
target = iris_datasets['target']

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=0)rom sklearn.model_selection import train_test_split
data = iris_dataset['data']
target = iris_dataset['target']

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=0)

NameError: name 'iris_datasets' is not defined

In [ ]:

from sklearn.model_selection import train_test_split

data = iris_dataset['data']
target = iris_dataset['target']

x_train, x_test, y_train, y_test = train_test_split(
    data, target, test_size=0.2, random_state=0
)

In [ ]:

print("Jumlah data x training = ", x_train.shape)
print("Jumlah data x testing = ", x_test.shape)
print("Jumlah data y training = ", y_train.shape)
print("Jumlah data y testing = ", y_test.shape)

Jumlah data x training =  (120, 4)
Jumlah data x testing =  (30, 4)
Jumlah data y training =  (120,)
Jumlah data y testing =  (30,)


In [ ]:

print("Jumlah data x training = ",x_train.shape)
print("Jumlah data x testing = ",x_test.shape)
print("Jumlah data y training = ",y_train.shape)
print("Jumlah data y testing = ",y_test.shape)

Jumlah data x training =  (120, 4)
Jumlah data x testing =  (30, 4)
Jumlah data y training =  (120,)
Jumlah data y testing =  (30,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [ ]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [ ]:
import numpy as np

x_baru = np.array([[3, 5.1, 5, 4.2]])
prediksi = knn.predict(x_baru)

print("Hasil Prediksi KNN =", prediksi)

Hasil Prediksi KNN = [2]


In [ ]:
x_baru

array([[3. , 5.1, 5. , 4.2]])

In [ ]:

prediksi = knn.predict(x_baru)
print("Hasil prediksi x_baru =", prediksi)
print("y_test =", y_test)

Hasil prediksi x_baru = [2]
y_test = [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


In [ ]:
x_baru

array([[3. , 5.1, 5. , 4.2]])

In [ ]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [ ]:

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    data, target, test_size=0.25, random_state=0
)

print("Jumlah data x training =", x_train.shape)
print("Jumlah data x testing =", x_test.shape)
print("Jumlah data y training =", y_train.shape)
print("Jumlah data y testing =", y_test.shape)

Jumlah data x training = (112, 4)
Jumlah data x testing = (38, 4)
Jumlah data y training = (112,)
Jumlah data y testing = (38,)


In [ ]:

from sklearn.metrics import accuracy_score

prediksi1 = knn.predict(x_test)
print("Hasil Akurasi =", accuracy_score(prediksi1, y_test) * 100)

Hasil Akurasi = 100.0


In [ ]:

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)

prediksi1 = knn.predict(x_test)
print("Hasil Akurasi =", accuracy_score(prediksi1, y_test) * 100)

Hasil Akurasi = 97.36842105263158


Tugas pertemuan ke 2 machine learning

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

iris_dataset = load_iris()
data = iris_dataset['data']
target = iris_dataset['target']

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.15, random_state=0)
print("Jumlah data x training =", x_train.shape)
print("Jumlah data x testing =", x_test.shape)
print("Jumlah data y training =", y_train.shape)
print("Jumlah data y testing =", y_test.shape)
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)
prediksi1 = knn.predict(x_test)
print("Hasil Akurasi =", accuracy_score(prediksi1, y_test) * 100)

Jumlah data x training = (127, 4)
Jumlah data x testing = (23, 4)
Jumlah data y training = (127,)
Jumlah data y testing = (23,)
Hasil Akurasi = 100.0


In [3]:

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

iris_dataset = load_iris()
data = iris_dataset['data']
target = iris_dataset['target']

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.255, random_state=0)
print("Jumlah data x training =", x_train.shape)
print("Jumlah data x testing =", x_test.shape)
print("Jumlah data y training =", y_train.shape)
print("Jumlah data y testing =", y_test.shape)
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)
prediksi2 = knn.predict(x_test)
print("Hasil Akurasi =", accuracy_score(prediksi2, y_test) * 100)

Jumlah data x training = (111, 4)
Jumlah data x testing = (39, 4)
Jumlah data y training = (111,)
Jumlah data y testing = (39,)
Hasil Akurasi = 97.43589743589743


In [4]:

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.3125, random_state=0)
print("Jumlah data x training =", x_train.shape)
print("Jumlah data x testing =", x_test.shape)
print("Jumlah data y training =", y_train.shape)
print("Jumlah data y testing =", y_test.shape)
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)
prediksi3 = knn.predict(x_test)
print("Hasil Akurasi =", accuracy_score(prediksi3, y_test) * 100)

Jumlah data x training = (103, 4)
Jumlah data x testing = (47, 4)
Jumlah data y training = (103,)
Jumlah data y testing = (47,)
Hasil Akurasi = 97.87234042553192
